<?xml version="1.0" encoding="UTF-8"?>
<tileset name="overworld" tilewidth="64" tileheight="64" tilecount="189" columns="21">
 <image source="overworld.png" width="1344" height="576"/>
 <tile id="0" probability="0"/>
 <tile id="1" probability="0"/>
 <tile id="2" probability="0"/>
 <tile id="3" probability="0"/>
 <tile id="4" probability="0"/>
 <tile id="5" probability="0"/>
 <tile id="6" probability="0"/>
 <tile id="7" probability="0"/>
 <tile id="8" probability="0"/>
 <tile id="9" probability="0"/>
 <tile id="10" probability="0"/>
 <tile id="11" probability="0"/>
 <tile id="12" probability="0"/>
 <tile id="13" probability="0"/>
 <tile id="14" probability="0"/>
 <tile id="15" probability="0"/>
 <tile id="16" probability="0"/>
 <tile id="17" probability="0"/>
 <tile id="18" probability="0"/>
 <tile id="19" probability="0"/>
 <tile id="20" probability="0"/>
 <tile id="21" probability="0"/>
 <tile id="22" probability="0"/>
 <tile id="23" probability="0"/>
 <tile id="24" probability="0"/>
 <tile id="25" probability="0"/>
 <tile id="26" probability="0"/>
 <tile id="27" probability="0"/>
 <tile id="28" probability="0"/>
 <tile id="29" probability="0"/>
 <tile id="30" probability="0"/>
 <tile id="31" probability="0"/>
 <tile id="32" probability="0"/>
 <tile id="33" probability="0"/>
 <tile id="34" probability="0"/>
 <tile id="35" probability="0"/>
 <tile id="36" probability="0"/>
 <tile id="37" probability="0"/>
 <tile id="38" probability="0"/>
 <tile id="39" probability="0"/>
 <tile id="40" probability="0"/>
 <tile id="41" probability="0"/>
 <tile id="42" probability="0"/>
 <tile id="43" probability="0"/>
 <tile id="44" probability="0"/>
 <tile id="45" probability="0"/>
 <tile id="46" probability="0"/>
 <tile id="47" probability="0"/>
 <tile id="48" probability="0"/>
 <tile id="49" probability="0"/>
 <tile id="50" probability="0"/>
 <tile id="51" probability="0"/>
 <tile id="52" probability="0"/>
 <tile id="53" probability="0"/>
 <tile id="54" probability="0"/>
 <tile id="55" probability="0"/>
 <tile id="56" probability="0"/>
 <tile id="57" probability="0"/>
 <tile id="58" probability="0"/>
 <tile id="59" probability="0"/>
 <tile id="60" probability="0"/>
 <tile id="61" probability="0"/>
 <tile id="62" probability="0"/>
 <tile id="63" probability="0"/>
 <tile id="64" probability="0"/>
 <tile id="65" probability="0"/>
 <tile id="66" probability="0"/>
 <tile id="67" probability="0"/>
 <tile id="68" probability="0"/>
 <tile id="69" probability="0"/>
 <tile id="70" probability="0.96"/>
 <tile id="71" probability="0"/>
 <tile id="72" probability="0"/>
 <tile id="73" probability="0"/>
 <tile id="74" probability="0"/>
 <tile id="75" probability="0"/>
 <tile id="76" probability="0"/>
 <tile id="77" probability="0"/>
 <tile id="78" probability="0"/>
 <tile id="79" probability="0"/>
 <tile id="80" probability="0"/>
 <tile id="81" probability="0"/>
 <tile id="82" probability="0"/>
 <tile id="83" probability="0"/>
 <tile id="84" probability="0"/>
 <tile id="85" probability="0"/>
 <tile id="86" probability="0"/>
 <tile id="87" probability="0"/>
 <tile id="88" probability="0"/>
 <tile id="89" probability="0"/>
 <tile id="90" probability="0"/>
 <tile id="91" probability="0"/>
 <tile id="92" probability="0"/>
 <tile id="93" probability="0"/>
 <tile id="94" probability="0"/>
 <tile id="95" probability="0"/>
 <tile id="96" probability="0"/>
 <tile id="97" probability="0"/>
 <tile id="98" probability="0"/>
 <tile id="99" probability="0"/>
 <tile id="100" probability="0"/>
 <tile id="101" probability="0"/>
 <tile id="102" probability="0"/>
 <tile id="103" probability="0"/>
 <tile id="104" probability="0"/>
 <tile id="105" probability="0"/>
 <tile id="106" probability="0"/>
 <tile id="107" probability="0"/>
 <tile id="108" probability="0"/>
 <tile id="109" probability="0"/>
 <tile id="110" probability="0"/>
 <tile id="111" probability="0"/>
 <tile id="112" probability="0"/>
 <tile id="113" probability="0"/>
 <tile id="114" probability="0"/>
 <tile id="115" probability="0"/>
 <tile id="116" probability="0"/>
 <tile id="117" probability="0"/>
 <tile id="118" probability="0"/>
 <tile id="119" probability="0"/>
 <tile id="120" probability="0"/>
 <tile id="121" probability="0"/>
 <tile id="122" probability="0"/>
 <tile id="123" probability="0"/>
 <tile id="124" probability="0"/>
 <tile id="125" probability="0"/>
 <tile id="126" probability="0"/>
 <tile id="127" probability="0"/>
 <tile id="128" probability="0"/>
 <tile id="129" probability="0"/>
 <tile id="130" probability="0"/>
 <tile id="131" probability="0"/>
 <tile id="132" probability="0"/>
 <tile id="133" probability="0"/>
 <tile id="134" probability="0"/>
 <tile id="135" probability="0"/>
 <tile id="136" probability="0"/>
 <tile id="137" probability="0"/>
 <tile id="138" probability="0"/>
 <tile id="139" probability="0"/>
 <tile id="140" probability="0"/>
 <tile id="141" probability="0"/>
 <tile id="142" probability="0"/>
 <tile id="143" probability="0"/>
 <tile id="144" probability="0"/>
 <tile id="145" probability="0"/>
 <tile id="146" probability="0"/>
 <tile id="147" probability="0"/>
 <tile id="148" probability="0"/>
 <tile id="149" probability="0"/>
 <tile id="150" probability="0"/>
 <tile id="151" probability="0"/>
 <tile id="152" probability="0"/>
 <tile id="153" probability="0"/>
 <tile id="154" probability="0"/>
 <tile id="155" probability="0"/>
 <tile id="156" probability="0"/>
 <tile id="157" probability="0"/>
 <tile id="158" probability="0"/>
 <tile id="159" probability="0"/>
 <tile id="160" probability="0"/>
 <tile id="161" probability="0"/>
 <tile id="162" probability="0"/>
 <tile id="163" probability="0"/>
 <tile id="164" probability="0"/>
 <tile id="165" probability="0"/>
 <tile id="166" probability="0"/>
 <tile id="167" probability="0"/>
 <tile id="168" probability="0"/>
 <tile id="169" probability="0"/>
 <tile id="170" probability="0"/>
 <tile id="171" probability="0.02"/>
 <tile id="172" probability="0.02"/>
 <tile id="173" probability="0"/>
 <tile id="174" probability="0"/>
 <tile id="175" probability="0"/>
 <tile id="176" probability="0"/>
 <tile id="177" probability="0"/>
 <tile id="178" probability="0"/>
 <tile id="179" probability="0"/>
 <tile id="180" probability="0"/>
 <tile id="181" probability="0"/>
 <tile id="182" probability="0"/>
 <tile id="183" probability="0"/>
 <tile id="184" probability="0"/>
 <tile id="185" probability="0"/>
 <tile id="186" probability="0"/>
 <tile id="187" probability="0"/>
 <tile id="188" probability="0"/>
</tileset>
